[package]
name = "bunner_cors_rs"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
regex = "1"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]
