name: coverage

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'examples/**'
      - 'tests/**'
  workflow_dispatch:

concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        run: |
          if ! command -v cargo-llvm-cov >/dev/null 2>&1; then
            cargo install cargo-llvm-cov
          fi

      - name: Generate coverage report
        run: |
          make coverage-lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: target/llvm-cov-target/lcov.info
          flags: rust
          fail_ci_if_error: true

      - name: Upload coverage summary
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/llvm-cov-target
