name: PR Checks

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'examples/**'
      - 'tests/**'
      - 'benches/**'
      - 'Makefile'
      - 'Cargo.toml'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
      - develop
      - 'release/**'
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'src/**'
      - 'examples/**'
      - 'tests/**'
      - 'benches/**'
      - 'Makefile'
      - 'Cargo.toml'
      - '.github/workflows/**'
  workflow_dispatch:

concurrency:
  group: pr-check-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: format check
        run: make format-check

      - name: lint
        run: make lint
